export enum Role {
  CUSTOMER = 'CUSTOMER',
  CHEF = 'CHEF',
  RESTAURANT_OWNER = 'RESTAURANT_OWNER',
  DELIVERY_PARTNER = 'DELIVERY_PARTNER',
  SUPPLIER = 'SUPPLIER',
  ADMIN = 'ADMIN',
  SUPERADMIN = 'SUPERADMIN',
  User = "User",
}
